### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by moomiji** [moomiji/docker-ddtvliverec#1]
下次功能性更新：今年末来年初

- [ ] 将原有的配置文件通过软连接至`/config`，方便配置
- [ ] 将`/config`中后加的文件通过脚本自动软连接至`/DDTVLiveRec`
- [ ] 支持上传模块
- [ ] `<add key="RoomConfiguration" value="./RoomListConfig.json" />`
- [ ] docker-compose + 标签

**Comment by moomiji** [comment]
DDTV5 VOLUME 可能有点意思的东西：https://github.com/MetaCubeX/mihomo/blob/Meta/Dockerfile

**Comment by moomiji** [comment]
3.0 细节代办
- [ ] Readme 链接至新分支
- [ ] doc 添加更新文档
- [ ] 添加 compose.yml
- [ ] 和重启更新和配置的自动更新关联
